# Generated by Django 3.0.8 on 2020-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('create_datetime', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'FileGroup',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=200, unique=True)),
                ('tag', models.TextField()),
                ('description', models.TextField(default='')),
                ('activate', models.BooleanField()),
                ('exist', models.BooleanField()),
                ('savetime_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'FileInfo',
            },
        ),
        migrations.CreateModel(
            name='FileInfo_has_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileInfo_id', models.IntegerField()),
                ('FileInfoDate_id', models.IntegerField()),
            ],
            options={
                'db_table': 'FileInfo_has_Date',
            },
        ),
        migrations.CreateModel(
            name='FileInfoDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('savetime', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'FileInfoDate',
            },
        ),
        migrations.CreateModel(
            name='GroupSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(default='', max_length=200)),
                ('group_search_result_log', models.FilePathField(max_length=200, unique=True)),
                ('group_id', models.IntegerField()),
                ('exsit', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'GroupSearchResult',
            },
        ),
        migrations.CreateModel(
            name='FileInfoHasGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileInfo_id', models.IntegerField()),
                ('FileGroup_id', models.IntegerField()),
            ],
            options={
                'db_table': 'FileInfoHasGroup',
                'unique_together': {('FileInfo_id', 'FileGroup_id')},
            },
        ),
    ]
